export const ritualServicesListMainPage = [
      { id: 1, src: require('../watermarked/RitualServices/ritualAgentTest.jpg'), alt: 'Зображення 1', title: 'Ритуальний агент', link: "/ritualagent", description: "Агент нашої ритуальної служби  – це досвідчений  фахівець, який бере на себе всі організаційні клопоти. Професійність і уважність до деталей дозволяють забезпечити підтримку родини у складний момент." },
      { id: 2, src: require('../watermarked/RitualServices/organizationFuneralsTest.jpg'), alt: 'Зображення 2', title: 'Організація похорону', link: "/funeralorganization", description: "Організація похоронуу «під ключ» – це збирання документів у відповідних інстанціях, необхідних для проведення похорону до самого похоронного обряду та поминальної трапези." },
      { id: 3, src: require('../watermarked/RitualServices/cremation.jpg'), alt: 'Зображення 3', title: 'Кремація', link: "/cremation", description: "Кремація — це сучасна та гідна форма прощання. Багато родин в Україні обирають її. Ми забезпечуємо повний супровід: від документів до передачі урни з прахом, з повагою до побажань родини." },
      { id: 4, src: require('../watermarked/RitualServices/hearse.jpg'), alt: 'Зображення 4', title: 'Автокатафалк', link: "/hearse", description: "Транспорт для перевезення тіла, супроводжуючих та ритуальних аксесуарів до місця поховання та для подальшого перевезення людей до зали для проведення поминальної церемонії." },
      { id: 5, src: require('../watermarked/RitualServices/ritualGoods.jpg'), alt: 'Зображення 5', title: 'Ритуальні товари', link: "/ritualgoods", description: "У магазині ритуальних товарів можна подивитися і купити: труни, вінки, хрести та інше ритуальне приладдя. Продаж пам’ятників відбувається за специфікаціями клієнта." },
      { id: 6, src: require('../watermarked/RitualServices/cargo200.jpg'), alt: 'Зображення 6', title: 'Вантаж 200', link: "/cargo", description: "Транспортування тіла – це складна процедура, з якою не впоратися поодинці. Агенти ритуального бюро «Проф Ритуал» допоможуть у перевезенні від місця смерті до місця поховання." },
      { id: 7, src: require('../watermarked/RitualServices/mortuaryServices.jpg'), alt: 'Зображення 7', title: 'Послуги холодильної камери', link: "/mortuaryservices", description: "Холодильна камера – тимчасове зберігання тіла у спеціальних умовах до поховання чи кремації." },
      { id: 8, src: require('../watermarked/RitualServices/memorialDinners.jpg'), alt: 'Зображення 8', title: 'Поминальні обіди', link: "/memorialdinners", description: "Наш похоронний агент може під’їхати 24 години на добу, первинна консультація – безкоштовно. У разі потреби ми можемо надати медичну та психологічну допомогу." },
      { id: 9, src: require('../watermarked/StoneOfMemoryPage/StoneOfMemoryPage.jpg'), alt: 'Зображення 9', title: 'Камінь Спогаду', link: "/stoneofmemory", description: "Іменні камені ручної роботи із праху людей і домашніх улюбленців." },
      { id: 10, src: require('../watermarked/RitualServices/musicalaccompaniment.jpg'), alt: 'Зображення 10', title: 'Музичний супровід', link: "/musicalaccompaniment", description: "Музичний супровід – організація живої або фонограми музики під час прощальної церемонії для створення особливої, зворушливої атмосфери." },
      { id: 11, src: require('../watermarked/MemoryCode/MemoryCode.jpg'), alt: 'Зображення 11', title: 'Код спогадів', link: "/memorycode", description: "Збереження спогадів у цифровому форматі за допомогою технологій QR- кодів." },
      { id: 12, src: require('../watermarked/PetsCremation/PetsCremation.jpg'), alt: 'Зображення 12', title: 'Кремація тварин', link: "/petscremation", description: "Спокійний та шанобливий спосіб зберегти пам’ять про улюбленця." },
];